"""Add day_of_week to video_metadata

Revision ID: 5cdf4eb091b7
Revises: d4912baf41f5
Create Date: 2025-10-03 15:15:11.360926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdf4eb091b7'
down_revision: Union[str, Sequence[str], None] = 'd4912baf41f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metadata', sa.Column('day_of_week', sa.String(length=20), nullable=True, comment="Day of week in Hebrew (e.g., 'ג'', 'ד'', 'ה'')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_metadata', 'day_of_week')
    # ### end Alembic commands ###
