"""add unique constraint to transcription_segments

Revision ID: 91cf6fe6caa1
Revises: 70925cd08f55
Create Date: 2025-10-06 12:01:06.492934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cf6fe6caa1'
down_revision: Union[str, Sequence[str], None] = '70925cd08f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transcription_segments_video_source_index', 'transcription_segments', ['video_id', 'source', 'segment_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transcription_segments_video_source_index', 'transcription_segments', type_='unique')
    # ### end Alembic commands ###
