"""Add video_metadata table

Revision ID: d4912baf41f5
Revises: 4d9669060f11
Create Date: 2025-10-03 15:09:40.054802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4912baf41f5'
down_revision: Union[str, Sequence[str], None] = '4d9669060f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_metadata',
    sa.Column('video_id', sa.String(length=20), nullable=False, comment='YouTube video ID (FK to videos)'),
    sa.Column('hebrew_date', sa.String(length=50), nullable=True, comment='Hebrew date extracted from title (e.g., \'ג\' תשרי התשפ"ו\')'),
    sa.Column('subject', sa.String(length=500), nullable=True, comment='Subject/topic extracted from title'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_metadata')
    # ### end Alembic commands ###
